/// Flutter icons SortIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SortIcons
///      fonts:
///       - asset: fonts/SortIcons.ttf
///
/// 
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class SortIcons {
  SortIcons._();

  static const _kFontFam = 'SortIcons';
  static const String? _kFontPkg = null;

  static const IconData sort_alpha_down = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sort_numeric_down = IconData(0xf162, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
